name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        node-version: 16.x
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test