name: Test

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Prepare
        run: yarn install --frozen-lockfile && turbo build --filter api-types

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
